Explicitly import '_Concurrency' module when building for Embedded (#1692)
This explicitly imports the `_Concurrency` module when building the
package for [Embedded
Swift](https://docs.swift.org/embedded/documentation/embedded/), since
in that context it's not implicitly imported.

### Motivation:

This resolves various errors when attempting to build for Embedded, such
as:

```
Test.swift:345:39: error: '_Concurrency' module not imported, required for async
```

### Checklist:

- [x] Code and documentation should follow the style of the [Style
Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should
be updated.