Disable library evolution when building for Embedded (#1691)
This disables library evolution when building the package for [Embedded
Swift](https://docs.swift.org/embedded/documentation/embedded/). This
resolves an error seen early on when attempting to build:

```
error: Library evolution cannot be enabled with embedded Swift.
```

### Checklist:

- [x] Code and documentation should follow the style of the [Style
Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should
be updated.