OpenBSD needs execinfo as well. (#1318)
Add OpenBSD to the CMake clause that adds libexecinfo.

### Motivation:

`swift test` fails on some projects with `ld: error: undefined reference
due to --no-allow-shlib-undefined: backtrace`; `backtrace` is provided
by `libexecinfo` on OpenBSD.

### Modifications:

Add OpenBSD to the CMake clause that adds libexecinfo.

### Checklist:

- [x] Code and documentation should follow the style of the [Style
Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should
be updated.