Modify `TestScoping` to work in Embedded Swift. (#1900)
This PR changes how we get the test scope provider from a trait in
Embedded Swift so that we're not trying to get an existential (`any
TestScoping`) from an existential (`any Trait`) which the compiler does
not allow. Instead, we add an underscored, default-implemented
requirement to `Trait` that does the type erasure for us.

Without this change, calling `scopeProvider(for:testCase:)` produces
this error:

> error: cannot specialize generic function or default protocol method
in this context [#EmbeddedRestrictions]

Non-Embedded Swift is unaffected.

### Checklist:

- [x] Code and documentation should follow the style of the [Style
Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should
be updated.