Require sendable userInfo values in JSON.withEncoding(of:userInfo:_:) (#955)
swift-foundation recently landed a change (in
https://github.com/swiftlang/swift-foundation/pull/764) which requires
`any Sendable` values in `JSONEncoder.userInfo`. This causes a build
failure in swift-testing:

```
JSON.swift:44:28: error: type 'Any' does not conform to the 'Sendable' protocol 
42 | 
43 |     // Set user info keys that clients want to use during encoding.
44 |     encoder.userInfo.merge(userInfo, uniquingKeysWith: { _, rhs in rhs})
   |                            `- error: type 'Any' does not conform to the 'Sendable' protocol
```

This PR adjusts our `userInfo:` parameter require `any Sendable` values.
The values we were passing to this utility were already sendable,
luckily.

### Checklist:

- [x] Code and documentation should follow the style of the [Style
Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should
be updated.