FreeBSD: bsearch pointer is Nonnull
The pointer passed into the compare function is marked Nonnull in the
FreeBSD stdlib header. This causes a build failure due to the unwrap.

```
error: cannot force unwrap value of non-optional type 'UnsafeRawPointer'
```

Fixing it for FreeBSD.